// @ts-nocheck
// .client/ is generated by hey-api

import { client } from './.client/services.gen.js';
import { SHOP_API_KEY, SHOP_API_URL } from 'astro:env/server';

if (!SHOP_API_KEY || !SHOP_API_URL) {
	throw new AstroError(
		'Falta la clave API de Storefront. Esto aún no está disponible públicamente, pero puede usar el adaptador simulado para ejecutar Storefront usted mismo. Consulte README > Servicios para obtener más detalles.',
	);
}

client.setConfig({
	baseUrl: SHOP_API_URL,
	headers: {
		Authorization: `Bearer ${SHOP_API_KEY}`,
	},
});

export * from './.client/services.gen.js';
export * from './.client/types.gen.js';
