[[redirects]]
  from = "https://maquiavelowines.netlify.app/*"
  to = "https://maquiavelowines.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  included_files = ["public/data/*.json"]

[dev]
  command = "pnpm dev"
  targetPort = 4321
  port = 8888
  framework = "#custom"

# ✅ Desactivar caché para archivos JSON estáticos
[[headers]]
  for = "public/data/*.json"
  [headers.values]
    Cache-Control = "no-store"

# ✅ Desactivar caché para la función get-products
[[headers]]
  for = "/.netlify/functions/get-products"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"

# ✅ Desactivar caché para la función update-stock
[[headers]]
  for = "/.netlify/functions/update-stock"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"

# ✅ Desactivar caché para la función login-admin
[[headers]]
  for = "/.netlify/functions/login-admin"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
