[[redirects]]
  from = "https://maquiavelowines.netlify.app/*"
  to = "https://maquiavelowines.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  included_files = ["public/data/*.json"]

[dev]
  command = "pnpm dev"
  targetPort = 4321
  port = 8888
  framework = "#custom"

[[headers]]
  for = "public/data/*.json"
  [headers.values]
    Cache-Control = "no-store"

