[[redirects]]
  from = "https://maquiavelowines.netlify.app/*"
  to = "https://maquiavelowines.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  role = "admin"

[functions]
  included_files = ["src/data/*.json"]
